Create URL with custom settings
bartificer/xkpasswd-js pull request #94
Opened 2024-06-20 23:19 UTC by irsheep

Generates a URL with the user custom configuration settings, the URL can be used to re-open the page with the same configuration.

The settings are converted from JSON to a CSV and encoded to a Base64 string, I took this approach as encoding the JSON object was creating a large URL.
When encoding to base64 some characters are replaced so the encoded string is URL save.

Example:
https://beta.xkpasswd.net/?c=ZW5nbGlzaCw0LDQsOCxDQVBJVEFMSVNFLEZJWEVELExRLElVQWtKVjRtS2kxZkt6MDZmSDRfTHk0NywyLDIsTk9ORSw4LFJBTkRPTSwsSVVBa0pWNG1LaTFmS3owNmZINF9MeTQ3LDIsMg

2024-06-22 12:58 UTC, hepabolu commented on src/web/settingsview.mjs
> +   * @private {string} savedSettingsLink - set time to show/hide elements
Please update the explanation of the savedSettingsLink. It now looks like a copy/paste error from the docs of aniTime

2024-06-22 13:13 UTC, hepabolu requested changes
At first, thanks a lot for this functionality. It looks very promising and a useful addition to the app.

I've tried your pull request and I found some issues. Please note that I have no intentions of turning this addition down, if my wording implies this, please ignore and regard it as an issue on my part.

The issues and suggestions below, are intended to improve the code in the pull request and make it more consistent with the current code base. If you don't want to spend more time, I'm more than happy to take it on.

![CleanShot 2024-06-22-14-26@2x](https://github.com/bartificer/xkpasswd-js/assets/7474858/c82a9499-611b-4f54-8c59-6cc3664812b2)

- when I press either the icon or the word 'copy' and then try to paste it in a new browser window I get 'undefined' as link. This also happens when I select the link first and then press the 'copy button'
- I think I found a bug: I selected the 'temporary' preset and changed the words to 3, see image below
![CleanShot 2024-06-22-14-44@2x](https://github.com/bartificer/xkpasswd-js/assets/7474858/54906b34-26cf-4a53-97da-8d5b011b8989)

If I then copy/paste the url to a new window, I get a stack trace

![CleanShot 2024-06-22-14-47@2x](https://github.com/bartificer/xkpasswd-js/assets/7474858/0a6ff5e1-329b-400f-88dd-5a9517cd6320)

Some suggestions:
- You added the 'custom' preset, which was also my idea to display when a custom preset was imported (either through the menu option or your link). So great idea 😉 However, it would be cool if you could also indicate that in the accordion bar, like the other presets. UPDATE: I can see that the could should already handle that, but it doesn't show up.

-  You created a separate config module to handle this link. Great stuff, but you put it in the lib directory. I may not have indicated this very well, but the intention is that the lib directory contains all the stuff that will be in the CLI library. 
Right now the config module is used in the index.mjs to handle the url during startup. In my mind this means the config module should be placed in the web directory.

2024-06-27 19:53 UTC, merged

2024-06-27 20:03 UTC, hepabolu commented
Thanks for the feature

2024-06-29 07:46 UTC, hepabolu commented
@irsheep This feature allows me to consolidate all loading and saving of configurations in one place. Thanks a lot! I need to rearrange and rename the code to match the other classes, but it will definitely keep its prominent functionality.

2024-09-29 01:51 UTC, podfeet commented
@irsheep I know this issue is closed but I wanted to tell you that in today's episode of Programming By Stealth,  @hepabolu taught @bbusschots and me about how XKPasswd-js has implemented Model View Controller, you got a huge shout out during the episode. at about 1 hour and 3 minutes, she told us about your PR and what a fantastic solution it was to give us a way to save a configuration. Then she went on to explain how because of MVC, it made it easier and cleaner to implement into the bigger project. 

I wanted to thank you for your contribution and to make sure you heard the show and the nice things said about you. At the link for the show notes for Programming By Stealth 171, you can listen to the whole thing, or to jump to 1:03 to hear us talk about your work.

https://pbs.bartificer.net/pbs171